version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres:12

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vending_machine

    volumes:
      - db:/data/postgres

    ports:
      - "5432:5432"

    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"



volumes:
  db: