server:
  port: 8000

  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vending_machine
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
